language: go
os:
  - linux
go:
  - "1.10.x"
  - master
before_install:
  - go get -u github.com/dgrijalva/jwt-go
  - go get -u github.com/go-sql-driver/mysql
  - go get -u github.com/gorilla/mux
  - go get -u github.com/jmoiron/sqlx
  - go get -u gopkg.in/yaml.v2

script:
  - go test ./...